### ISSUE TITLE
上传后无法使用

### ISSUE THREAD

**Issue by news0762** [jiemo9527/jiemo9527.github.io#1]
作者你好，很喜欢你的导航模板。但是将源文件上传到根目录后，网页打开异常。请问是什么问题？谢谢
--- layout: default active_key: home --- {%- for section in site.data.links -%}
{%- for category in section.categories && category.index<6-%}
{{ category.name }}
{% for link in category.links %}{% if link.icon %}{% endif %}{{ link.name }}{% endfor %}
{%- endfor -%}
{%- endfor -%}

**Comment by jiemo9527** [comment]
首先本项目没有部署到服务器上，而是基于github-pages服务。参考文档：https://jekyllrb.com/docs/github-pages/
如果你需要部署到服务器则需要先安装环境Ruby开发环境、Jekyll以及bundler gems.
